name: publish-pacakge
run-name: publish to mooncakes
on: 
  release: 
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH
      - name: moon version
        run: |
          moon version --all
          moonrun --version
      - name: moon check
        run: |
          moon check
          moon check --target wasm
          moon check --source-dir example/snake
          moon check --source-dir example/snake --target wasm
      - name: publish
        run: |
          rm -r example
          echo "$env:SECRET" > ~/.moon/credentials.json
          moon publish
          rm ~/.moon/credentials.json
        env:
          SECRET: ${{ secrets.MOONCAKES_MOONBITLANG_TOKEN }}